### ISSUE TITLE
Repo migrated to where?

### ISSUE THREAD

**Issue by jaysondc** [android/app-bundle-samples#34]
>This repo has been migrated to github.com/android/app-bundle. Please check that repo for future updates. Thank you!

github.com/android/app-bundle redirects me back here to github.com/android/app-bundle-samples.

Is this the right repo?

**Comment by keyboardsurfer** [comment]
Indeed it is. @codingjeremy can you update https://github.com/googlearchive/android-dynamic-features ?

**Comment by codingjeremy** [comment]
Sorry, I can see how this confused everyone.

The old repo is now https://github.com/**googlearchive/android-dynamic-features**. It was gh/**googlesamples/android-dynamic-features** before I archived it to our official org for archived repos.

In that README, it points you to github.com/android/**app-bundle**

That was the original name of the new repo, but we have since changed it from **app-bundle** to **app-bundle-samples**. Github has a nice feature where it just redirects your original name to the new name so you don't lose anyone, so that's what is going on here.

I can go ask for permissions to update that link back, but it is technically pointing to the right location (though through redirects). ^_^;;
